name: Django CI

# Triggers
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Jobs
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      # Step 4: Run Pre-commit hooks
      - name: Run Pre-commit
        run: |
          pre-commit run --all-files

      # Step 5: Run Django System Check
      - name: Run Django Check
        run: |
          cp .env.example .env
          python manage.py check

      # Step 6: Build Docker images
      - name: Build Docker Images
        run: docker compose build
